
all: test_matrix

test_matrix: \
    test_matrix.cpp \
    matrix.h \
    matrix_util.h \
    matrix_cholesky_decomp.tcc \
    matrix_lu_decomp.tcc \
    matrix_qr_decomp.tcc \
    matrix_sv_decomp.tcc
